--- name:default
# Left limit of the vertical opening angle in radians
left_limit: -0.7853981633974483
# Lower limit of the horizontal opening angle in radians
lower_limit: -0.535292481
# Larger distances (meter) are discarded
maximum_distance: 80.0
# Smaller distances (meter) are discarded
minimum_distance: 1.0
# name of the camera in the scene file
name: 'velodyne'
# Vertical angular resolution in radians
resolution_horizontal: 0.002792526
# Vertical angular resolution in radians
resolution_vertical: 0.023212879
# Right limit of the vertical opening angle in radians
right_limit: 0.7853981633974483
# Upper limit of the horizontal opening angle in radians
upper_limit: 0.186226631
