--- name:default
# The name of the imu frame.
imu_frame: imu
# name of the node in the scene file from which to get the imu data
name: 300-100-SPBORB01-209-001_sim.001
# The name of the world frame.
world_frame: world
